# Generated by Django 2.1.15 on 2020-07-25 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('place', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sample/')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('crimetype', models.CharField(default='None', max_length=120)),
                ('duration', models.IntegerField(default=1, null=True)),
                ('start_duration', models.IntegerField(default=1, null=True)),
                ('end_duration', models.IntegerField(default=1, null=True)),
                ('classified', models.BooleanField(default='False')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Camera')),
            ],
        ),
        migrations.AddField(
            model_name='suspect',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Video'),
        ),
    ]
