# Generated by Django 2.1.15 on 2020-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='classified',
            field=models.BooleanField(default=False),
        ),
    ]
